#! /bin/bash
set -x
set -e

function killeverything {
	pkill -9 qemu-system-x86
	pkill -9 gdb
	pkill -9 ddd
}

module=$1
test_name=$2

if [ ! -d "/pintos/$module" ]; then
	module="$(cat /pintos/make_check_module)"
	test_name=$1
fi

if [ -z "$test_name" ]; then
	echo "No test name provided" >&2
	exit 2
fi

trap "killeverything" SIGINT

(cd /pintos/examples && make)
cd "/pintos/$module" && make
cd build

ARGS=${@:3}
if [ "$ARGS" != "" ]; then
	ARGS=" $ARGS"
fi

pintos -v --gdb --filesys-size=2 --swap-size=2 -p /pintos/examples/$2 -a $(basename $2) -- -f run "$(basename $2)$ARGS" < /dev/null &

ddd -gdb --eval-command="debugpintos"  -debugger pintos-gdb "/pintos/$module/build/kernel.o" 2>&1 > /dev/null &

wait
